### ISSUE TITLE
Pobieranie danych z teleman

### ISSUE THREAD

**Issue by PiterEL** [slawekmikula/epguide#42]
Witam
Zauwazylem ze chyba cos zmienili na teleman bo program mi pobiera i na niektorych kanalach jako tytul mam w tvheadend rok produkcji filmu... Prosze zweryfikuj to. Używam wersji 1.9.3 i najnowszej wersji tvheadend 4.1.211

**Comment by PiterEL** [comment]
Please fix it....

**Comment by slawekmikula** [comment]
Zgłoszenie mało przejrzyste. Brak informacji jaki kanał, kiedy pobierane. Sprawdziłem dzisiaj na kanałach POLSAT, TVP-1 oraz Polsat-Sport. Poprawnie pobiera. Zgłoszenie do zamknięcia.

**Comment by PiterEL** [comment]
Witam
Zobacz na zrzut ekranu u mnie... Mam najnowszego TVHeadend 4.1.307
Wczoraj skasowałem wszystkie pliki cache od epguide i plik w tvheadend od epg i niestety dalej to samo.
![epg](https://cloud.githubusercontent.com/assets/4134018/8371300/dfcc3122-1bd5-11e5-942b-dd2912598f91.jpg)

**Comment by slawekmikula** [comment]
Dołącz proszę plik xml z wynikami działania epguide dla tego co pojawia się w TVHeadend. Będzie materiałem wejściowym do sprawdzenia.

**Comment by PiterEL** [comment]
a jak pobrać XML ?

**Comment by kamiKAC** [comment]
Witam
Ja używam epguide do MythTV. Mam ten sam problem.

Po wydaniu polecenia:

tv_grab_pl_epguide --config-file DVB-T.xmltv --output DVB-T.xml

dostaję w DVB-T.xml m.in taki wpis:

 <programme start="20150629061500 +0200" stop="20150629080000 +0200" channel="TVN">
    <title>Mango</title>
    <desc><![CDATA[telezakupy]]></desc>
    <category language="en">News/Current affairs</category>
    <category language="pl">telezakupy</category>
  </programme>
  <programme start="20150629080000 +0200" stop="20150629083500 +0200" channel="TVN">
    <title></title>
    <desc><![CDATA[serial fabularno-dokumentalny
W tym odcinku: Krzysztof Dziób poszukuje córki klientów, która zaginęła tuż przed swoim ślubem. Istnieje podejrzenie, że została porwana dla okupu. Wkrótce wychodzi na jaw, że dziewczynę uprowadził jej były partner. Mężczyzna zeznaje, że chciał uchronić ją przed popełnieniem życiowego błędu, gdyż jej obecny narzeczony to gangster.
Opis: Marzena Fliegel i Maciek Friedek prowadzą biuro detektywistyczne. Ich wieloletnie doświadczenie pozwala im podjąć się najtrudniejszych spraw. Współpracują z nimi Krzysztof Dziób, który zna wschodnie sztuki walki i znakomicie radzi sobie w sytuacjach ekstremalnych, oraz asystenci: Alicja Kalinowska, Karolina Lutczyn, Roksana Roguś, Marcin Halbiniak. Detektywi pomagają ludziom w dramatycznych chwilach - przy porwaniach i zaginięciach najbliższych. Często dostają nietypowe zlecenia i wspierają stróżów prawa przy ujmowaniu przestępców.]]></desc>
    <date>2010</date>
    <category language="en">Show/Game show</category>
    <category language="pl">serial fabularno-dokumentalny</category>
    <icon src="http://media.teleman.pl/photos/470x265/Detektywi_1.jpeg"/>
    <country>Polska</country>
    <rating system="pl"><value>12</value></rating>
  </programme>
  <programme start="20150629083500 +0200" stop="20150629093500 +0200" channel="TVN">
    <title>Ugotowani</title>
    <desc><![CDATA[program kulinarno-rozrywkowy]]></desc>
    <category language="en">Leisure hobbies</category>
    <category language="pl">program kulinarno-rozrywkowy</category>
    <icon src="http://media.teleman.pl/photos/470x265/Ugotowani.jpeg"/>
    <episode-num system="onscreen">6</episode-num>
  </programme>
  <programme start="20150629093500 +0200" stop="20150629103500 +0200" channel="TVN">
    <title>Kuchenne rewolucje</title>
    <sub-title>Imperium Smaku, Łódź</sub-title>
    <desc><![CDATA[program rozrywkowy]]></desc>
    <category language="en">Leisure hobbies</category>
    <category language="pl">program rozrywkowy</category>
    <icon src="http://media.teleman.pl/photos/470x265/Kuchenne-Rewolucje.jpeg"/>
    <episode-num system="onscreen">9</episode-num>
  </programme>
  <programme start="20150629103500 +0200" stop="20150629113500 +0200" channel="TVN">
    <title></title>
    <desc><![CDATA[serial paradokumentalny
W tym odcinku: Dwa miesiące temu 16-letni Hubert przeniósł się do nowego liceum, po tym jak w poprzedniej szkole wpadł w złe towarzystwo i uzależnił się od narkotyków. Chłopak niedawno zakończył leczenie i wyszedł z nałogu. O jego problemach wie wychowawczyni, Jolanta Żabińska. Wkrótce Hubert przyłapuje kolegów z klasy jak palą marihuanę. Wśród nich jest Marcelina, która bardzo mu się podoba. Po zażyciu dopalaczy jeden z licealistów traci przytomność. Nauczyciele podejrzewają, że to Hubert dał im narkotyki. 15-letnia Sabina od dwóch miesięcy spotyka się z 18-letnim Staszkiem. Chłopak jest gitarzystą w zespole metalowym. Gimnazjalistka chce mu zaimponować i postanawia zrobić sobie dla niego tatuaż. Gdy rodzice nie wyrażają zgody na zabieg, nastolatka z pomocą przyjaciółki tatuuje sobie imię chłopaka za pomocą igły i tuszu. Wkrótce rana zaczyna bardzo boleć, a Sabina dostaje wysokiej gorączki.
Opis: Codzienne perypetie współczesnych nastolatków, uczniów klas gimnazjalnych i licealnych. Młodzi ludzie zmagają się z wieloma problemami typowymi dla ich wieku, jak poszukiwanie własnej tożsamości czy potrzeba akceptacji. Wyzwania, jakie stawia przed nimi świat, oraz sprawy, z którymi muszą sobie radzić, wielokrotnie znajdują ujście w ich zachowaniu. Negowanie autorytetów, bunt, kradzieże, prześladowania i poszukiwanie nowych wrażeń to część wątków zaprezentowanych w serialu. W każdym z odcinków widzowie poznają historie uczniów, w których ważną rolę odegrają nauczyciele. Dzięki ich życzliwej pomocy nastolatkowie uświadomią sobie, że z trudnej sytuacji można znaleźć wyjście i najbardziej skomplikowany problem da się mądrze rozwiązać. Tłem im przygód jest Gimnazjum nr 105 i Liceum Ogólnokształcącego nr 44 w Krakowie, które znajdują się pod opieką dyrektora, Stanisława Chlebowskiego (Tadeusz Łomnicki).]]></desc>
    <date>2014</date>
    <category language="en">Show/Game show</category>
    <category language="pl">serial paradokumentalny</category>
    <icon src="http://media.teleman.pl/photos/470x265/Szkola-38_rLcSz92.jpg"/>
    <country>Polska</country>
    <rating system="pl"><value>12</value></rating>
  </programme>
  <programme start="20150629113500 +0200" stop="20150629123500 +0200" channel="TVN">
    <title></title>
    <desc><![CDATA[serial paradokumentalny
W tym odcinku: Maryla i Waldek żyją na granicy ubóstwa. Kobieta opiekuje się teściem, którego renta stanowi ważną część jej budżetu domowego. Śmierć mężczyzny zbiega się z wypadkiem Waldka. Maryla postanawia ukryć ciało na strychu i udawać, że zaginął. Od listonosza odbiera jego rentę. Tymczasem nieświadomy niczego Waldek zgłasza zniknięcie ojca na policję.
Opis: Realistycznie przedstawione historie rodzin, których spokój został zburzony przez tajemnice, niedomówienia lub ingerencję osób trzecich. Każdy odcinek serialu to odrębna opowieść o bliskich osobach, które w obliczu nowych faktów muszą radzić sobie z dramatycznym splotem wydarzeń. Na przykład syn okazuje się owocem zdrady żony, rodzice prowadzą podwójne życie, córka cierpi na zaburzenia odżywiania itp. Losy bohaterów mają być dowodem na to, że każdy problem można rozwiązać, choć wymaga to mnóstwa dobrej woli, odwagi i refleksji nad swoim życiem.]]></desc>
    <date>2012</date>
    <category language="en">Show/Game show</category>
    <category language="pl">serial paradokumentalny</category>
    <icon src="http://media.teleman.pl/photos/470x265/Ukryta-Prawda.jpeg"/>
    <country>Polska</country>
    <rating system="pl"><value>12</value></rating>
  </programme>

Mam nadzieję, że teraz uda się znaleźć przyczynę.
Jeśli potrzebne byłyby dodatkowe informacje to służę pomocą.

Pozdrawiam
--
kamiKAC

**Comment by slawekmikula** [comment]
Właśnie uruchomiłem z opcjami

i otrzymałem:
```xml 
 <programme start="20150629113500 +0200" stop="20150629123500 +0200" channel="TVN">
    <title>Ukryta prawda (60)</title>
    <desc><![CDATA[serial paradokumentalny
W tym odcinku: Maryla i Waldek żyją na granicy ubóstwa. Kobieta opiekuje się teściem, którego renta stanowi ważną część jej budżetu domowego. Śmierć mężczyzny zbiega się z wypadkiem Waldka. Maryla postanawia ukryć ciało na strychu i udawać, że zaginął. Od listonosza odbiera jego rentę. Tymczasem nieświadomy niczego Waldek zgłasza zniknięcie ojca na policję.
Opis: Realistycznie przedstawione historie rodzin, których spokój został zburzony przez tajemnice, niedomówienia lub ingerencję osób trzecich. Każdy odcinek serialu to odrębna opowieść o bliskich osobach, które w obliczu nowych faktów muszą radzić sobie z dramatycznym splotem wydarzeń. Na przykład syn okazuje się owocem zdrady żony, rodzice prowadzą podwójne życie, córka cierpi na zaburzenia odżywiania itp. Losy bohaterów mają być dowodem na to, że każdy problem można rozwiązać, choć wymaga to mnóstwa dobrej woli, odwagi i refleksji nad swoim życiem.]]></desc>
    <date>2012</date>
    <category language="en">Show/Game show</category>
    <category language="pl">serial paradokumentalny</category>
    <icon src="http://media.teleman.pl/photos/470x265/Ukryta-Prawda.jpeg"/>
    <country>Polska</country>
    <rating system="pl"><value>12</value></rating>
  </programme>
```

Tytuł się pojawia. Natomiast u ciebie tytułu w ukrytej prawdzie nie ma. Rozumiem, że opis pojawia się OK (te tagi CDATA nie przeszkadzają MythTV) ? Próbowałem kilkukrotnie wywołać i ten sam efekt. Korzystacie z wersji z HEAD ? Podaj zawartość pliku konfiguracji. 

Może kombinuję, ale może telemanowi nie podoba się pobieranie danych hurtowo ? W końcu trochę omijamy ich serwis.

**Comment by PiterEL** [comment]
Moj plik konfiguracji:

timestamp = 2014-10-23 09:11:52.973264
channels = teleman|TVP-1, teleman|TVP-2, teleman|TVN, teleman|13-Ulica, gazeta|337, teleman|Ale-Kino, teleman|Animal-Planet, teleman|ATM-Rozrywka, teleman|AXN, teleman|BBC-Cbeebies, teleman|BBC-Entertainment, teleman|CBS-Action, teleman|CBS-Europa, teleman|Comedy-Central-Family, teleman|Discovery-Channel, teleman|Discovery-Science, teleman|Discovery-Turbo-Xtra, teleman|Eska-TV, teleman|Eurosport, teleman|Filmbox, teleman|Filmbox-Extra, teleman|Filmbox-Family, teleman|Filmbox-HD, teleman|Kino-Polska, teleman|Kuchnia-TV, teleman|MiniMini, teleman|MTV-Polska, teleman|National-Geographic, teleman|Planete, teleman|Polonia-1, teleman|Polsat, teleman|Polsat-2, teleman|Polsat-Cafe, teleman|Polsat-Film, teleman|Polsat-News, teleman|Polsat-Play, teleman|Polsat-Sport, teleman|Polsat-Sport-Extra, teleman|Polsat-Sport-News, teleman|Viasat-Explorer, teleman|Viasat-History, teleman|Viasat-Nature, teleman|Religia-TV, teleman|Superstacja, teleman|Tele-5, teleman|Travel-Channel, teleman|teleTOON-plus, teleman|TLC, teleman|TTV, teleman|TV4, teleman|TV6, teleman|Puls, teleman|Puls-2, teleman|TVN24, teleman|TVN-Siedem, teleman|TVN-Style, teleman|TVN-Turbo, teleman|TVP-Historia, teleman|TVP-Info, teleman|TVP-Kultura, teleman|TVP-Polonia, teleman|TVP-Rozrywka, teleman|TVP-Seriale, teleman|TVP-Sport, teleman|TVS, teleman|Universal-Channel, teleman|VIVA-Polska, teleman|TVP-ABC, teleman|TV-Trwam, teleman|AXN-White, teleman|BBC-Knowledge, teleman|BBC-Lifestyle, teleman|Eurosport-2, teleman|Nat-Geo-Wild, teleman|Viasat-Nature, teleman|Stopklatka-TV, teleman|TVN-24-Biznes-i-Swiat, teleman|FOX, teleman|Foxlife, teleman|Fokus-TV, gazeta|400, gazeta|41, gazeta|90, teleman|BBC-Brit, teleman|BBC-Earth, teleman|FOX-Comedy, teleman|Discovery-Life, teleman|TVN-Fabula
days = 14
split-title = False
add-original-title-to-title = False
add-year-to-title = False
add-age-rating-to-title = False
log-level = 20

**Comment by kamiKAC** [comment]
Mój konfig:
`timestamp = 2014-04-06 14:08:35.541884
channels = ATM-Rozrywka, Eska-TV, Polsat, Polsat-Sport-News, Puls, Puls-2, Stopklatka-TV, TTV, TV4, TV6, TVN, TVN-Siedem, TVP-1, TVP-2, TVP-ABC, TVP-H
istoria, TVP-Info, TVP-Kultura, TVP-Polonia, TVP-Rozrywka
days = 7
split-title = True
add-original-title-to-title = False
add-year-to-title = False
add-age-rating-to-title = False
log-level = 20`

Można spróbować odczekiwać losową ilość czasu pomiędzy pobraniami kolejnych stron, co powinno uśpić czujność telemana ;-) 

Co do CDATA to jakoś MythTV je usuwa przed wprowadzeniem opisu do SQL.

Pozdrawiam

**Comment by PiterEL** [comment]
Proszę powiedzcie mi jak odpalic epguide z polecenia tv_grab_pl_epguide np dla jednego kanału i wygenerować plik xmltv w danej scieżce ? Potrzebuje plik aby do pomcy tvheadenda wyslac,

**Comment by PiterEL** [comment]
Zauważyłem że epguide nie pokazuje w TVHeadend programów które mają numery odcinków w nazwie na teleman.pl oraz chyba podtytułu typu xxx:hhhh

W załączniku zrzuty z polsatu gdzie pokazuje nazwy ok programów które maja tylko tytuł a juz jak na telemanie jest numer w nawiasach to tego nie pokazuje...

![epg polsat](https://cloud.githubusercontent.com/assets/4134018/8404775/0d855a7c-1e50-11e5-9b13-37ba4c6ba15a.jpg)
![polsat teleman](https://cloud.githubusercontent.com/assets/4134018/8404776/0ec2ae26-1e50-11e5-8f20-cf28f86c41fa.jpg)

**Comment by kamiKAC** [comment]
Przykład wygenerowania pliku z programem masz w moim poście powyżej. Musisz tylko wyedytować plik konfiguracji (lub stworzyć nowy), żeby zawierał tylko 1 program.

**Comment by PiterEL** [comment]
Dałem takie polecenie i poszło:

hts@PePe_DS713:~/epguide-1.9.3$ sudo ./epguide_run -d 2015-06-30 -c FOX -p teleman -f xmltv

tylko nie wiem gdzie on mi wygenerował plik xmltv ?

**Comment by kamiKAC** [comment]
Na ekran wygenerował. Trzeba dopisać -o plik.xmltv

**Comment by PiterEL** [comment]
Ok poszło. Mam plik xmltv. 
http://www8.zippyshare.com/v/nbjh3Hz3/file.html

**Comment by PiterEL** [comment]
A jak zrobić aby zapisał dla całego tygodnia czyli dla 7 dni ? Bo tak wskazuje konkretną datę... Bo na TVHeadend potrzebuja dla całego tygodnia.

**Comment by kamiKAC** [comment]
Już wiem, dlaczego nie mam tytułów :)
Wywala się po dodaniu --split-title. Z tego co zauwazyłem nie lubi nawiasów i znaku zapytania w tytule.

Mam nadzieję, że autor znajdzie chwilkę, żeby to poprawić. Ja niestety kompletnie nie kumam pythona, więc sie nie podejmuję grzebania w kodzie.

Pozdrawiam

**Comment by slawekmikula** [comment]
Widzicie, potraficie :) Parsowanie tytułu jest dość dużym kawałkiem kodu. Dla zainteresowanych jest w pliku TelemanData.py od linii 100 do 168. Mam prośbę o podanie jeszcze przykładowych tytułów (albo linków do strony telemana dla tych wydarzeń), które powodują problemy. Bardzo ułatwi mi to pracę.
Ja po prostu obecnie nie używam epguide do pobierania programu na masową skalę i nie jestem w stanie tego wyłapać.

**Comment by slawekmikula** [comment]
dodatkowo jakbyście mogli dołączyć wyjście z programu z opcją --verbose. Tam będzie trochę informacji o parsowaniu tytułu. Może wskazać mi to miejsce gdzie jest problem.

**Comment by slawekmikula** [comment]
chyba poprawione, problem wynikał z niepoprawnego parsowania tytułu na stronie szczegółów programu, w przypadku gdy mieliśmy film lub podobne. sprawdźcie wersję HEAD

**Comment by PiterEL** [comment]
A możesz mi powiedzieć jak pobrać wersję HEAD ? Np w zipie wtedy podmienie sobie na synology...

**Comment by slawekmikula** [comment]
ok zamykam zgłoszenie :)

Co do innych parserów to można wpisać nowe issue na każdy parser z osobna, ale musi się ktoś znaleźć, kto to zaimplementuje. Przykłady już są, tylko trzeba zrobić :)

**Comment by slawekmikula** [comment]
zamykam

**Comment by PiterEL** [comment]
Rozumiem że ty nie podejmiesz się już tego ?
