### ISSUE TITLE
format beesmart 

### ISSUE THREAD

**Issue by msoffice2005** [slawekmikula/epguide#43]

**Comment by slawekmikula** [comment]
Co to za program (beesmart) ? Link ? Czy jest gdzieś definicja DTD/Schema do tego formatu (XML) ?

**Comment by msoffice2005** [comment]
Krótki opis Beesmarta:
http://88.220.36.150/epguide/BeeSmart-description(1).html
Strona główna:
http://www.beenius.tv/
Opis api z którego korzysta:
http://88.220.36.150/epguide/BeeSmart_LITE_3_0_OpenAPI.html
Przewodnik administracyjny:
http://88.220.36.150/epguide/BeeSmart_LITE_3_0_Administration_Guide_fixed.html
Przykładowe pliki XML:
http://88.220.36.150/epguide/xmldata.tar
Wersje w formacie PDF dostepne sa pod linkiem:
http://88.220.36.150/epguide/

Beesmart w wersji 3.2 lite wystepuje jako bezpłatny z api 1.0.2, niestety aktualny beesmart 4.2 jest już płatnym rozwiązaniem. Wiele rozwiązań Middleware korzysta właśnie z formatu epg który został wdrożony przez beesmarta.
