### ISSUE TITLE
teleman nie działa

### ISSUE THREAD

**Issue by piotrasd** [slawekmikula/epguide#44]
witam chyba cos zmienili na telemanie, bo epguide juz nawet nie pokazuje listy dostepnych kanałow

**Comment by slawekmikula** [comment]
Proszę przeczytać informację na stronie głównej. Zapewne z tym jest to związane. Zamykam bez reakcji.

**Comment by ghost** [comment]
Tak zmienili a pan Slawek juz nie chce wspierac projektu. Ja tez nie wiem jak poprawic i co aby to dzialalo. Szkoda... teraz zostalem zmuszony ze tylko z gazety mi pobiera...
